graph_route = {
    'Cikarang': [('Bekasi', 21, 'KRL')],
    'Bekasi': [('Jatinegara', 19, 'KRL')],
    'Jatinegara': [('Matraman', 2, 'KRL'), ('Senen Sentral', 13, 'KRL'), ('Bekasi', 19, 'KRL')],
    'Matraman': [('Jatinegara', 2, 'KRL'), ('Manggarai', 2, 'KRL'), ('Senen Sentral', 32, 'TJ'), ('LRT Cawang', 30, 'TJ')],
    'Manggarai': [('Matraman', 2, 'KRL'), ('Sudirman / Dukuh Atas', 13, 'KRL'), ('Jakarta Kota', 20, 'KRL'), ('Cikoko', 5, 'KRL')],
    'Sudirman / Dukuh Atas': [('Manggarai', 13, 'KRL'), ('Pancoran', 13, 'LRT'), ('Bendungan Hilir / Semanggi', 11, 'TJ'), ('Tanah Abang', 5, 'KRL'), ('Bundaran HI', 8, 'TJ'), ('Bendungan Hilir / Semanggi', 4, 'MRT'), ('Bundaran HI', 3, 'MRT')],
    'Tanah Abang': [('Sudirman / Dukuh Atas', 5, 'KRL'), ('Kebayoran', 11, 'KRL'), ('Duri', 8, 'KRL')],
    'Duri': [('Tanah Abang', 8, 'KRL'), ('Grogol', 4, 'KRL')],
    'Tangerang': [('Taman Kota', 20, 'KRL')],
    'Taman Kota': [('Tangerang', 20, 'KRL'), ('Grogol', 5, 'KRL')],
    'Grogol': [('Taman Kota', 5, 'KRL'), ('Duri', 4, 'KRL'), ('Bendungan Hilir / Semanggi', 38, 'TJ')],
    'Serpong': [('Pondok Ranji', 14, 'KRL')],
    'Pondok Ranji': [('Serpong', 14, 'KRL'), ('Kebayoran', 7, 'KRL')],
    'Kebayoran': [('Kebayoran', 7, 'KRL'), ('Tanah Abang', 11, 'KRL'), ('Blok M / ASEAN', 18, 'TJ')],
    'Bogor': [('Citayam', 20, 'KRL')],
    'Citayam': [('Bogor', 20, 'KRL'), ('Depok', 10, 'KRL')],
    'Depok': [('Citayam', 10, 'KRL'), ('Cikoko', 23, 'KRL')],
    'Cikoko': [('Depok', 23, 'KRL'), ('Manggarai', 5, 'KRL'), ('Pancoran', 4, 'LRT'), ('Pancoran', 5, 'TJ'), ('LRT Cawang', 3, 'LRT'), ('LRT Cawang', 4, 'TJ')],
    'Bekasi Barat': [('LRT Cawang', 28, 'LRT')],
    'LRT Cawang': [('Bekasi Barat', 28, 'LRT'), ('Cikoko', 3, 'LRT'), ('Cikoko', 4, 'TJ'), ('Matraman', 30, 'TJ')],
    'Pancoran': [('Sudirman / Dukuh Atas', 13, 'LRT'), ('Cikoko', 4, 'LRT'), ('Cikoko', 5, 'TJ'), ('Bendungan Hilir / Semanggi', 12, 'TJ'), ('Blok M / ASEAN', 15, 'TJ')],
    'Lebak Bulus': [('Blok M / ASEAN', 20, 'MRT')],
    'Blok M / ASEAN': [('Lebak Bulus', 20, 'MRT'), ('Bendungan Hilir / Semanggi', 6, 'MRT'), ('Bendungan Hilir / Semanggi', 30, 'TJ'), ('Pancoran', 15, 'TJ'), ('Kebayoran', 18, 'TJ')],
    'Bendungan Hilir / Semanggi': [('Blok M / ASEAN', 6, 'MRT'), ('Sudirman / Dukuh Atas', 4, 'MRT'), ('Blok M / ASEAN', 30, 'TJ'), ('Sudirman / Dukuh Atas', 11, 'TJ'), ('Pancoran', 12, 'TJ'), ('Grogol', 38, 'TJ')],
    'Bundaran HI': [('Sudirman / Dukuh Atas', 3, 'MRT'), ('Sudirman / Dukuh Atas', 8, 'TJ'), ('Monas', 10, 'TJ')],
    'Monas': [('Jakarta Kota', 28, 'TJ'), ('Juanda', 9, 'TJ'), ('Bundaran HI', 10, 'TJ')],
    'Juanda': [('Senen Sentral', 25, 'TJ'), ('Monas', 9, 'TJ')],
    'Senen Sentral': [('Jatinegara', 13, 'KRL'), ('Juanda', 25, 'TJ'), ('Matraman', 32, 'TJ')],
}